[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mss>=10.0.0",
    "numpy>=2.2.4",
    "pyautogui>=0.9.54",
    "ultralytics>=8.3.23",
]
